### ISSUE TITLE
De-reference all properties in `export * from ...`

### ISSUE THREAD

**Issue by mprobst** [angular/sickle#47]
When compiling `export * from 'foo';` to CommonJS module format, we end up with code like this:

```js
function __export(m) { for (var k in m) exports[k] = m; }
__export(require('somemodule'));
```

Now surprisingly this works in Closure Compiler when replacing `require` with `goog.require`. It simply patches the `exports` to be the module name (which is a global symbol) and then the right properties end up on the right objects (yay!).

However when importing a property that was re-exported like this, Closure Compiler complains about a missing property. It's possible to shut that off (`--jscomp_off=missingProperties`), but that seems overall dangerous - for example, dead code elimination might kill that property.

If sickle was to "de-reference" and re-export the particular symbols, this would avoid the problem for the time being, and allow us to continue using the hacky CommonJS --> `goog.require` transformation without having to rely on ES6 modules.

An alternative, possibly cleaner, solution would be to convert all module imports to `goog.module` and `goog.require` within sickle (including the `*` dereferencing). This would break the second compilation pass - TypeScript would no longer understand all those imports. However we have already type checked, so at that point we could just ignore all errors and emit.

WDYT? @martine @rkirov

**Comment by mprobst** [comment]
Ping?

**Comment by martine** [comment]
How would sickle know which symbols to re-export?  It sounds like it would need to be a semantic translation, when currently it's purely syntactic.  Maybe we already need to do something like that due to #38 though.  And I guess we've now changed tsc_wrapped such that sickle has access to this info.

I like relying on Closure ES6 support because that part of Closure is actively being improved, and it makes our semantics match more closely.  But there must be some downside -- what is it?

Third option: we could even disallow this expression for now.  If we pretend TS is a new syntax for goog.require code we can say "sorry, must write it in a for goog.require understands", until one of the above paths works out.

**Comment by mprobst** [comment]
* Yeah, we'd have to stop being purely syntactic. I have the feeling we'll get there sooner or later anyway, though.
* Re ES6 support, the Closure team considers this experimental/unsupported, and many things don't work (referencing code across bazel-bin, import base paths for external modules, etc) doesn't work. It's also kind of nice to have the same output for devmode and prod, at least module wise.
* Disallowing sounds good, but Angular 2 heavily relies on this, so that's a no go, too.

I'll try and find some time to poke at this tomorrow a bit more.

**Comment by martine** [comment]
Now that Sickle runs after semantic checking, we can easily make use of types etc. so this shouldn't be so bad.  It may even be the case that the data you need is available on the SourceFile passed in.

**Comment by alexeagle** [comment]
This is also a problem for closure compiler to re-order the imports. Using `--dependency_mode=STRICT` fails to find any require statements so the whole application is pruned away.
See http://b/27545272

**Comment by martine** [comment]
I spent some time looking at this.  Some interesting stuff I learned:

A.ts:
```js
export var foo = 3;
```

B.ts:
```js
export * from './A';
export var foo = 'hello';
```

C.ts:
```js
import {foo} from './B';
// what is the type of 'foo' here?
```

The answer is `string`.  I guess it shadows, effectively.
But if a single file exports the same name multiple times there's a specific compiler error about it.

This is a long way of getting to the point, which is that `export * from ...` doesn't affect the types/symbol table of the current file as all -- the type checker doesn't appear to even traverse the referenced module in that statement, because it doesn't need to.  I think.  Not sure.

I'm sure this is possible, but I'm still digging...

**Comment by martine** [comment]
In rollup it appears that whoever is *first* wins when there is conflicting exports(!)

http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20*%20from%20'.%2Fa.js'%3B%5Cnexport%20*%20from%20'.%2Fb.js'%3B%5Cn%22%7D%2C%7B%22name%22%3A%22a.js%22%2C%22code%22%3A%22export%20var%20foo%20%3D%203%3B%22%7D%2C%7B%22name%22%3A%22b.js%22%2C%22code%22%3A%22export%20var%20foo%20%3D%204%3B%22%7D%5D%7D

**Comment by martine** [comment]
@alexeagle wrote:

found another issue in google3 (maybe):

core.ts:
```
export * from './src/core/metadata';
export * from './src/core/util';
export * from './src/core/prod_mode';
export * from './src/core/di';
export * from './src/facade/facade';
export {enableProdMode} from 'angular2/src/facade/lang';
```

result from blaze
```
third_party/javascript/angular2/github/modules/angular2/core.ts:1:829: Duplicate identifier 'enableProdMode'.
third_party/javascript/angular2/github/modules/angular2/core.ts:2:9: Duplicate identifier 'enableProdMode'.
```

**Comment by martine** [comment]
I asked our local ES6 expert about these issues and he said:

 there are two different cases. One is:

// (1)
export * from 'something'; // where 'something' exports 'foo'
export var foo = 3;

Another is:

// (2)
// Both of these modules export 'foo'
export * from 'something';
export * from 'another';

Now assume some other module imports 'foo'.

For (1), the "shadowing" behavior is correct per spec. This is because ResolveExport always checks for local exports before checking for star exports. See steps 4 and 10 of https://tc39.github.io/ecma262/#sec-resolveexport

For (2), the correct behavior is to throw during module instantiation. See step 12.c of https://tc39.github.io/ecma262/#sec-moduledeclarationinstantiation (that bit of the spec invokes ResolveExport, which returns "ambiguous" if it finds multiple star exports that overlap).

**Comment by martine** [comment]
I believe this is now correct -- we handle case (1) above with the latest change, and (2) should already be disallowed by the TypeScript compiler.

**Comment by martine** [comment]
Still busted on this case:
```js
export * from 'foo';  // includes bar
export {bar} from 'foo2';
```

**Comment by alexeagle** [comment]
thanks, I get past this now when compiling angular2 app with closure compiler.
